### ISSUE TITLE
FEAT: Add a better looking search button in header

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#50]
**Screenshot**
![Screenshot 2023-06-01 at 6 49 29 PM](https://github.com/aashay28/GitBoard/assets/108337259/ca158d7e-97df-45a5-bb01-7d1a56888202)

**Comment by murat114** [comment]
Hi, @aashay28
Can I take on the task.

**Comment by aashay28** [comment]
@murat114 sure, assigned to you.

**Comment by aashay28** [comment]
@murat114

**Comment by murat114** [comment]
@aashay28 I will try the button again tonight

**Comment by aashay28** [comment]
@murat114 Okay, but please make sure that you won't push the package-lock.json file.

**Comment by murat114** [comment]
@aashay28 Okay, all right :)

**Comment by aashay28** [comment]
@murat114 PR has been merged but please hide the button when the devices are small.
create a issue and work on it accordingly
