### ISSUE TITLE
Add hover effect on cards

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#51]
![Screenshot 2023-06-01 at 6 53 38 PM](https://github.com/aashay28/GitBoard/assets/108337259/dc55c348-2cd6-4613-837a-658f81586ae4)

**Comment by yi-heng-chen** [comment]
@aashay28 Can you assign this to me? I have the code ready.

**Comment by aashay28** [comment]
@yi-heng-chen sure.
