### ISSUE TITLE
Search button on the home page doesn't work

### ISSUE THREAD

**Issue by yi-heng-chen** [aashay28/GitBoard#57]
**Describe the bug**
The search button does not work when clicked

**To Reproduce**
1. Go to home page
2. Enter the search term per the required format e.g. language:java
3. Click on search
4. No result listed

**Expected behavior**
A list of projects that match the criteria should be listed

**Screenshots**

**Desktop (please complete the following information):**
<img width="1043" alt="image" src="https://github.com/aashay28/GitBoard/assets/136173916/5a7d13ca-f5ae-425a-ac0a-40aba901547c">

**Smartphone (please complete the following information):**

**Comment by aashay28** [comment]
@yi-heng-chen would you like to work on it ?

**Comment by yi-heng-chen** [comment]
@aashay28 Yes, please assign it to me and I will work on it.

**Comment by aashay28** [comment]
@yi-heng-chen I'm very pleased with your work. I just wanted to bring to your attention a small styling issue that I think you may have missed, please check the new issues.
