### ISSUE TITLE
The dropdown should be positioned below the search bar

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#59]
![Screenshot 2023-06-13 at 9 26 48 AM](https://github.com/aashay28/GitBoard/assets/108337259/08e19218-293f-485b-8530-10af8682c0f2)

**Comment by DanielXing1103** [comment]
Hi, how do I run this project locally? `npm start` doesn't seem to work and I can't find the script name. Thank you.

**Comment by aashay28** [comment]
@DanielXing1103 Use "npm run dev" to run the project locally

**Comment by aashay28** [comment]
@DanielXing1103 Check the [Contributing Guide](https://github.com/aashay28/GitBoard/blob/main/contributing.md) for more information, It has been updated.

**Comment by aashay28** [comment]
> I would like to try fixing this

@N-coder-bot  I'll confirm with Daniel and let you know.

**Comment by karthickbharathi1** [comment]
Hi @aashay28  ,  can you assign me this issue?

**Comment by X-sena-X** [comment]
Hi @aashay28 , I can help you with this issue . Please give me reply whether to go forward.

**Comment by aashay28** [comment]
> Hi @aashay28 , can you assign me this issue?

Did a great job.
