### ISSUE TITLE
Update readme to include project setup for local development

### ISSUE THREAD

**Issue by ychen100** [aashay28/GitBoard#62]
**Acceptance Criteria**
Have a dedicate section in the readme that list out the steps to run the application locally for development.

**Comment by aashay28** [comment]
@yi-heng-chen The local steps have been updated in the contributing.md file. I think it would be a good idea to update them in the read file as well.

**Comment by ychen100** [comment]
@aashay28 sorry I was a bit busy these days, you can unassigne me from this ticket. Anyone who's keen can pick it up. Should be able to continue contributing this weekend l.

**Comment by aashay28** [comment]
> @aashay28 sorry I was a bit busy these days, you can unassigne me from this ticket. Anyone who's keen can pick it up. Should be able to continue contributing this weekend l.

okay whenever you are available, you can work on it.
