### ISSUE TITLE
[bugfix] wrong language label is shown when Java is selected in /projects page

### ISSUE THREAD

**Issue by ychen100** [aashay28/GitBoard#63]
**Describe the bug**
The wrong label is shown when Java is selected on the `/projects` page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/project`
2. Select `Java` as the language
3. `JavascriptJava` is shown

**Expected behaviour**
`Java` should be displayed as the label

**Screenshots**
![image](https://github.com/aashay28/GitBoard/assets/136173916/d082f2e9-529c-46a5-8a03-7d0553666056)

**Comment by aashay28** [comment]
@yi-heng-chen assigned to you. please move forward with the task.
