### ISSUE TITLE
Add scale effect on hover of project cards

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#64]

**Comment by tymnec** [comment]
Assign this to me! 😄

**Comment by aashay28** [comment]
@tymnec please start working on it.

**Comment by aashay28** [comment]
@tymnec I think hover:scale-100 hover:duration-300 would be fine

**Comment by tymnec** [comment]
But Now I have added hover:scale-110 and duration-700. Actually that was smooth 😄

**Comment by tymnec** [comment]
Should I change it?

**Comment by aashay28** [comment]
> Should I change it?

I have verified that and its perfect.
Keep it up mate. Great job !
