### ISSUE TITLE
Hide default user image and name

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#85]
![Screenshot 2023-06-16 at 5 06 43 PM](https://github.com/aashay28/GitBoard/assets/108337259/00336263-72b7-47a3-89f3-39a3f16ac1db)

**Comment by ajay2827** [comment]
@aashay28 could you assign this to me please,

**Comment by aashay28** [comment]
> @aashay28 could you assign this to me please, so that i can start working on this 

Over to you, make sure that necessary files must be changed. Good luck mate.

**Comment by aashay28** [comment]
Great work. Keep it up.
