### ISSUE TITLE
On Keypress enter it should navigate to connections page

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#86]
![Screenshot 2023-06-16 at 5 13 14 PM](https://github.com/aashay28/GitBoard/assets/108337259/ac9911d6-317e-4c9a-b2a6-4bf02e2591fb)

**Comment by ajay2827** [comment]
@aashay28 could you assign this issue to me , so that i can work on it

**Comment by aashay28** [comment]
Great work, please get the task assigned before generate the PR. Thank you.
