### ISSUE TITLE
Need to change two svg on connection page

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#87]
![Screenshot 2023-06-16 at 5 15 36 PM](https://github.com/aashay28/GitBoard/assets/108337259/aae971e8-6be0-4ab7-83b3-425ce1fd8b8f)

**Comment by realrohitgurav** [comment]
Hi @aashay28 , can you give more details as to what you would like to change in this issue? :)

**Comment by aashay28** [comment]
> Hi @aashay28 , can you give more details as to what you would like to change in this issue? :)

@realrohitgurav replace the two svg element and place the relatable svg at following and not following cards.

**Comment by srivenkatharsha** [comment]
Pull request [submitted](https://github.com/aashay28/GitBoard/pull/93) for updated SVG icons. 

Preview: 

![image](https://github.com/aashay28/GitBoard/assets/109057156/15e90056-53dd-47e3-9e78-acdd86460bd4)
