### ISSUE TITLE
Rename the button text in projects

### ISSUE THREAD

**Issue by aashay28** [aashay28/GitBoard#98]
### Task
1. Change the "View" button text to "Repo".
2. Change the "Preview" button to "Website". And if there is no preview available disable the website button.

![Rename](https://github.com/aashay28/GitBoard/assets/108337259/35db09c1-f547-4c75-9761-0b2ad4293655)

**Comment by Shangli-Hou** [comment]
I would love to contribute

**Comment by aashay28** [comment]
@Shangli-Hou that's great
